
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mainproject_development
  adapter: postgresql
  username: harry
  password: harry123
  host: localhost


  test:
  <<: *default
  database: mainproject_test
  
production:
  <<: *default
  database: mainproject_production
  
  username: harry
  password: harry123
